<a href="https://colab.research.google.com/github/muhammaddavie23-eng/Aljabar_Matrix_-Muhammad-Davie-Mardaprilo_PSTI_C/blob/main/Vectors_and_Vector_Transposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NO 1**

In [2]:
#buat vector x dengan ukuran 3x1

import numpy as np

x = np.array([99, 60, 51]) # type argument is optional, e.g.: dtype=np.float16
x

array([99, 60, 51])

In [3]:
#hitung panjang vector x

len(x)

3

In [4]:
#tampilkan ukuran vector x

x.shape

(3,)

In [5]:
#tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [6]:
#akses elemen pertama dari vector x
x[0]

np.int64(99)

In [ ]:
#tampilkan tipe data elemen pertama dari vector x
x[0]

# **NO** **2**

In [11]:
#lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([99, 60, 51])

In [12]:
#tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [16]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y.T
y_t

array([[67],
       [69],
       [66]])

In [17]:
#tampilkan ukuran dari vector x_y
y_t.shape

(3, 1)

## **NO** **3**

# **Pytorch**

In [21]:
#lakukan soal nomor 2 menggunakan pytorch dan tensorflow

import torch as pt
x_pt = pt.tensor(x)
x_pt


tensor([99, 60, 51])

In [22]:
x_pt.shape

torch.Size([3])

In [23]:
y_pt = pt.tensor(y)
y_pt

tensor([[67, 69, 66]])

In [24]:
y_pt.shape

torch.Size([1, 3])

In [26]:
x_pt = x_pt.T
x_pt

tensor([99, 60, 51])

In [27]:
x_pt.shape

torch.Size([3])

# **Tensorflow**

In [33]:
import tensorflow as tf
x_tf = tf.Variable([9, 19, 3], dtype = tf.int32)
print(x_tf)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 9, 19,  3], dtype=int32)>


In [39]:
x_tf.shape

TensorShape([3])

In [35]:
y_tf = tf.Variable([88, 76, 12], dtype = tf.int32)
print(y_tf)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([88, 76, 12], dtype=int32)>


In [40]:
y_tf.shape

TensorShape([3])

In [36]:
x_tf = tf.transpose(x_tf)
print(x_tf)

tf.Tensor([ 9 19  3], shape=(3,), dtype=int32)


In [42]:
x_tf.shape

TensorShape([3])